[tool.poetry]
name = "pandas-units-extension"
version = "0.1.0"
description = "Units extension array for pandas based on astropy"
authors = ["Jan Pipek <jan.pipek@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
pandas = "^0.25.3"
astropy = "^4.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
